# Generated by Django 5.1.5 on 2025-01-30 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(default='a delicious recipe', max_length=25)),
                ('dish_type', models.CharField(choices=[('first dish', [('soup', 'soup'), ('broth', 'broth'), ('chowder', 'chowder'), ('other', 'other')]), ('second dish', [('porridge', 'porridge'), ('meat dish', 'meat dish'), ('fish dish', 'fish dish'), ('salad', 'salad'), ('other', 'other')]), ('desserts', [('cake', 'cake'), ('tart', 'tart'), ('muffin', 'muffin'), ('ice-cream', 'ice-cream'), ('milk', 'milk'), ('other', 'other')]), ('beverages', [('tea', 'tea'), ('cacao', 'cacao'), ('coffe', 'coffee'), ('cocktail', 'cocktail'), ('juice', 'juice'), ('other', 'other')])], default='dish type', max_length=30)),
                ('cooking_level', models.CharField(choices=[('E', 'Simple'), ('A', 'Average'), ('C', 'Complex')], default='simple', max_length=1)),
                ('portion_qty', models.IntegerField(default=1)),
                ('cooking_time', models.IntegerField(default=10, help_text='Enter cooking time in minutes')),
                ('ingredients', models.TextField(default='oranges, 1, kg', help_text='Enter ingredient, quantity and units', max_length=500)),
                ('directions', models.TextField(default='first step is ...', max_length=2000)),
                ('taste', models.CharField(blank=True, default='spicy', max_length=170)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date edited')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('recipe_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.ManyToManyField(to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipecategory')),
                ('recipe_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('recipe_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
