# Generated by Django 5.1.5 on 2025-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion_qty',
            field=models.IntegerField(default=1, help_text='Enter servings', verbose_name='Serving'),
        ),
    ]
