# Generated by Django 5.1.5 on 2025-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_portion_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='for example, oranges, 1, kg', help_text='Enter ingredient, quantity and units', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portion_qty',
            field=models.IntegerField(default=1, verbose_name='Serving'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='taste',
            field=models.CharField(blank=True, default='spicy', help_text='Describe taste', max_length=170),
        ),
    ]
